// Electron IPC 通道常量：主进程、preload 和测试共享，避免字符串漂移。
export const IPC = {
  GET_PREFERENCES: "get-preferences",
  SAVE_PREFERENCES: "save-preferences",
  GET_OFFICIAL_SETTINGS_SOURCES: "get-official-settings-sources",
  UPDATE_OFFICIAL_SETTINGS_SOURCES: "update-official-settings-sources",
  READ_CONFIG_FILE: "read-config-file",
  SAVE_CONFIG_FILE: "save-config-file",
  LIST_DIR: "list-dir",
  LIST_CLAUDE_OUTPUT_STYLES: "list-claude-output-styles",
  CREATE_CLAUDE_OUTPUT_STYLE: "create-claude-output-style",
  LIST_CLAUDE_PLUGINS: "list-claude-plugins",
  LIST_CLAUDE_MARKETPLACES: "list-claude-marketplaces",
  CHECK_CLAUDE_PLUGIN_UPDATES: "check-claude-plugin-updates",
  CHECK_CODEX_PLUGIN_UPDATES: "check-codex-plugin-updates",
  UPDATE_CLAUDE_PLUGIN: "update-claude-plugin",
  UPDATE_CLAUDE_MARKETPLACE: "update-claude-marketplace",
  UPDATE_CODEX_PLUGIN: "update-codex-plugin",
  UPDATE_CODEX_MARKETPLACE: "update-codex-marketplace",
  SET_PLUGIN_ENABLED: "set-plugin-enabled",
  LIST_SKILLS: "list-skills",
  CHECK_TOOL_LATEST_VERSION: "check-tool-latest-version",
  UPDATE_TOOL_CLI: "update-tool-cli",
  DETECT_TOOLS: "detect-tools",
  OPEN_IN_VSCODE: "open-in-vscode",
  REVEAL_IN_FINDER: "reveal-in-finder",
  OPEN_EXTERNAL_URL: "open-external-url",
};
