import type { VisualConfigSchema } from "../components/visual-config/schemaTypes";

// CLAUDE_SETTINGS_SCHEMA 存储 Claude settings.json 的可视化字段元数据。
export const CLAUDE_SETTINGS_SCHEMA: VisualConfigSchema = {
  id: "claude-settings",
  title: "Claude settings.json",
  format: "json",
  groups: [
    {
      id: "model",
      title: "模型与推理",
      description: "控制 Claude Code 会话默认模型、备用模型和推理相关行为。",
      fields: [
        {
          path: "model",
          title: "默认模型",
          description: "Claude Code 默认使用的模型别名或完整模型名。",
          control: "text",
          scope: "用户级、项目级、本地级均可覆盖。",
          risk: "normal",
        },
        {
          path: "fallbackModel",
          title: "Fallback 模型",
          description: "默认模型不可用时尝试使用的备用模型。",
          control: "text",
          scope: "用户级、项目级、本地级均可覆盖。",
          risk: "normal",
        },
        {
          path: "effortLevel",
          title: "推理强度",
          description: "控制 Claude Code 在任务中投入的推理强度。",
          control: "select",
          options: [
            { value: "low", label: "low" },
            { value: "medium", label: "medium" },
            { value: "high", label: "high" },
            { value: "xhigh", label: "xhigh" },
            { value: "max", label: "max" },
          ],
          scope: "用户级、项目级、本地级均可覆盖。",
          risk: "normal",
        },
        {
          path: "prompt_suggestions",
          title: "提示建议",
          description: "控制会话是否生成下一步提示建议。",
          control: "switch",
          scope: "用户级配置。",
          risk: "experimental",
        },
        {
          path: "verbose",
          title: "详细输出",
          description: "控制 CLI 是否默认启用详细输出。",
          control: "switch",
          scope: "用户级、项目级、本地级均可覆盖。",
          risk: "normal",
        },
      ],
    },
    {
      id: "permissions",
      title: "权限",
      description: "控制工具允许、拒绝、询问和默认权限模式。",
      fields: [
        {
          path: "permissions.defaultMode",
          title: "默认权限模式",
          description: "新会话默认采用的权限模式。",
          control: "select",
          options: [
            { value: "default", label: "default" },
            { value: "acceptEdits", label: "acceptEdits" },
            { value: "bypassPermissions", label: "bypassPermissions" },
            { value: "plan", label: "plan" },
          ],
          scope: "用户级、项目级、本地级均可覆盖。",
          risk: "danger",
        },
        {
          path: "permissions.allow",
          title: "允许规则",
          description: "允许直接执行的工具或命令规则。",
          control: "string-list",
          defaultValue: [],
          scope: "用户级、项目级、本地级均可覆盖。",
          risk: "danger",
        },
        {
          path: "permissions.deny",
          title: "拒绝规则",
          description: "始终拒绝执行的工具或命令规则。",
          control: "string-list",
          defaultValue: [],
          scope: "用户级、项目级、本地级均可覆盖。",
          risk: "normal",
        },
        {
          path: "permissions.ask",
          title: "询问规则",
          description: "执行前需要确认的工具或命令规则。",
          control: "string-list",
          defaultValue: [],
          scope: "用户级、项目级、本地级均可覆盖。",
          risk: "normal",
        },
      ],
    },
    {
      id: "runtime",
      title: "运行时与扩展",
      description: "控制环境变量、Hooks、MCP、工具列表、插件和市场。",
      fields: [
        {
          path: "env",
          title: "环境变量",
          description: "启动 Claude Code 时注入的环境变量。",
          control: "json-object",
          scope: "用户级、项目级、本地级均可覆盖。",
          risk: "sensitive",
          sensitive: true,
        },
        {
          path: "hooks",
          title: "Hooks",
          description: "按生命周期事件执行的命令 hook 配置。",
          control: "json-object",
          scope: "用户级、项目级、本地级均可覆盖。",
          risk: "danger",
        },
        {
          path: "mcpServers",
          title: "MCP Servers",
          description: "Claude Code 可连接的 MCP server 配置。",
          control: "json-object",
          scope: "用户级、项目级、本地级均可覆盖。",
          risk: "sensitive",
          sensitive: true,
        },
        {
          path: "allowedTools",
          title: "允许工具",
          description: "默认启用的内置工具列表。",
          control: "string-list",
          scope: "用户级、项目级、本地级均可覆盖。",
          risk: "danger",
        },
        {
          path: "disallowedTools",
          title: "禁用工具",
          description: "默认禁用的内置工具列表。",
          control: "string-list",
          scope: "用户级、项目级、本地级均可覆盖。",
          risk: "normal",
        },
        {
          path: "tools",
          title: "工具集合",
          description: "指定会话可使用的内置工具集合。",
          control: "string-list",
          scope: "用户级、项目级、本地级均可覆盖。",
          risk: "danger",
        },
        {
          path: "enabledPlugins",
          title: "启用插件",
          description: "按插件 ID 控制是否启用已安装插件。",
          control: "json-object",
          scope: "用户级配置。",
          risk: "normal",
        },
        {
          path: "disabledPlugins",
          title: "禁用插件",
          description: "按插件 ID 控制是否禁用已安装插件。",
          control: "json-object",
          scope: "用户级配置。",
          risk: "normal",
        },
        {
          path: "extraKnownMarketplaces",
          title: "额外市场",
          description: "Claude Code 额外识别的插件市场配置。",
          control: "json-object",
          scope: "用户级配置。",
          risk: "normal",
        },
      ],
    },
    {
      id: "updates-ui",
      title: "更新与界面",
      description: "控制自动更新、状态栏和界面行为。",
      fields: [
        {
          path: "autoUpdates",
          title: "自动更新",
          description: "控制 Claude Code 是否自动检查并应用更新。",
          control: "switch",
          scope: "用户级配置。",
          risk: "normal",
        },
        {
          path: "autoUpdatesChannel",
          title: "更新渠道",
          description: "控制自动更新使用的发布渠道。",
          control: "select",
          options: [
            { value: "stable", label: "stable" },
            { value: "latest", label: "latest" },
          ],
          scope: "用户级配置。",
          risk: "normal",
        },
        {
          path: "statusLine",
          title: "状态栏",
          description: "自定义 Claude Code 状态栏渲染方式。",
          control: "json-object",
          scope: "用户级配置。",
          risk: "normal",
        },
      ],
    },
  ],
};
