import type { VisualConfigSchema } from "../components/visual-config/schemaTypes";

// CODEX_CONFIG_SCHEMA 存储 Codex config.toml 的可视化字段元数据。
export const CODEX_CONFIG_SCHEMA: VisualConfigSchema = {
  id: "codex-config",
  title: "Codex config.toml",
  format: "toml",
  groups: [
    {
      id: "model-provider",
      title: "模型与 Provider",
      description: "控制 Codex 默认模型、评审模型和 provider 连接信息。",
      fields: [
        {
          path: "model_provider",
          title: "模型 Provider",
          description: "选择默认模型提供方。",
          control: "text",
          scope: "用户级配置；项目级配置不应覆盖 provider。",
          risk: "normal",
        },
        {
          path: "model",
          title: "默认模型",
          description: "Codex agent 默认使用的模型。",
          control: "text",
          scope: "用户级、项目级配置。",
          risk: "normal",
        },
        {
          path: "review_model",
          title: "评审模型",
          description: "Codex review 命令默认使用的模型。",
          control: "text",
          scope: "用户级、项目级配置。",
          risk: "normal",
        },
        {
          path: "model_providers",
          title: "Provider 详情",
          description: "Provider URL、wire API、认证方式和 websocket 能力。",
          control: "toml-object",
          scope: "用户级配置；包含机器本地和认证相关设置。",
          risk: "sensitive",
          sensitive: true,
        },
      ],
    },
    {
      id: "runtime-policy",
      title: "运行策略",
      description: "控制推理、响应存储、沙箱、审批、网络和通知。",
      fields: [
        {
          path: "model_reasoning_effort",
          title: "推理强度",
          description: "控制模型推理投入程度。",
          control: "select",
          options: [
            { value: "minimal", label: "minimal" },
            { value: "low", label: "low" },
            { value: "medium", label: "medium" },
            { value: "high", label: "high" },
            { value: "xhigh", label: "xhigh" },
            { value: "max", label: "max" },
          ],
          scope: "用户级、项目级配置。",
          risk: "normal",
        },
        {
          path: "disable_response_storage",
          title: "禁用响应存储",
          description: "控制是否禁止服务端保存响应内容。",
          control: "switch",
          scope: "用户级配置。",
          risk: "normal",
        },
        {
          path: "sandbox_mode",
          title: "沙箱模式",
          description: "控制 agent 执行命令时的文件系统访问范围。",
          control: "select",
          options: [
            { value: "read-only", label: "read-only" },
            { value: "workspace-write", label: "workspace-write" },
            { value: "danger-full-access", label: "danger-full-access" },
          ],
          scope: "用户级、项目级配置。",
          risk: "danger",
        },
        {
          path: "approval_policy",
          title: "审批策略",
          description: "控制命令执行前是否需要用户审批。",
          control: "select",
          options: [
            { value: "untrusted", label: "untrusted" },
            { value: "on-request", label: "on-request" },
            { value: "never", label: "never" },
          ],
          scope: "用户级、项目级配置。",
          risk: "danger",
        },
        {
          path: "network_access",
          title: "网络访问",
          description: "控制 Codex 是否启用网络访问。",
          control: "select",
          options: [
            { value: "enabled", label: "enabled" },
            { value: "disabled", label: "disabled" },
          ],
          scope: "用户级、项目级配置。",
          risk: "danger",
        },
        {
          path: "sandbox_permissions",
          title: "沙箱权限",
          description: "对沙箱能力进行额外声明。",
          control: "string-list",
          scope: "用户级、项目级配置。",
          risk: "danger",
        },
        {
          path: "notify",
          title: "通知命令",
          description: "回合结束时执行的通知命令。",
          control: "string-list",
          scope: "用户级配置；通常是机器本地路径。",
          risk: "sensitive",
        },
      ],
    },
    {
      id: "extensions-ui",
      title: "扩展与界面",
      description: "控制功能开关、桌面设置、TUI、MCP、插件、市场和项目 trust。",
      fields: [
        {
          path: "features",
          title: "功能开关",
          description: "Codex 实验或渐进发布功能开关。",
          control: "toml-object",
          scope: "用户级配置。",
          risk: "experimental",
        },
        {
          path: "desktop",
          title: "Desktop 设置",
          description: "Codex 桌面应用相关设置。",
          control: "toml-object",
          scope: "用户级配置。",
          risk: "experimental",
        },
        {
          path: "tui",
          title: "TUI 设置",
          description: "Codex CLI 终端界面设置。",
          control: "toml-object",
          scope: "用户级配置。",
          risk: "normal",
        },
        {
          path: "mcp_servers",
          title: "MCP Servers",
          description: "Codex 可连接的 MCP server 配置。",
          control: "toml-object",
          scope: "用户级配置；包含机器本地路径和环境变量。",
          risk: "sensitive",
          sensitive: true,
        },
        {
          path: "plugins",
          title: "插件",
          description: "Codex 已安装插件启用状态。",
          control: "toml-object",
          scope: "用户级配置。",
          risk: "normal",
        },
        {
          path: "marketplaces",
          title: "插件市场",
          description: "Codex 插件市场来源和更新时间。",
          control: "toml-object",
          scope: "用户级配置。",
          risk: "normal",
        },
        {
          path: "projects",
          title: "项目信任",
          description: "项目路径到 trust_level 的映射。",
          control: "toml-object",
          scope: "用户级配置。",
          risk: "danger",
        },
      ],
    },
  ],
};
